name: Truffle CI

on:
  
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.14.0'

    - name: Install Ganache
      run: npm install -g ganache-cli
      # run: |
      #   curl -OL https://github.com/trufflesuite/ganache-cli/releases/download/v7.0.0/ganache-cli-7.0.0-x86_64.AppImage
      #   chmod +x ganache-cli-7.0.0-x86_64.AppImage
      #   sudo mv ganache-cli-7.0.0-x86_64.AppImage /usr/local/bin/ganache-cli

    - name: Start Ganache
      run: ganache-cli --deterministic --gasLimit 8000000 > ganache.log 2>&1 & echo $! > ganache.pid

    # - name: Show Ganache folders
    #   run: ls -l /usr/local/bin/ganache-cli

    - name: Show Ganache Log
      run: cat ganache.log

    - name: Install Truffle
      run: npm install -g truffle

    - name: Compile contracts
      run: truffle compile

    # - name: Docker ps
    #   run: docker ps

    - name: Run tests
      run: truffle test

    - name: Deploy contracts to Ganache
      run: truffle migrate --network development
